- ActivitySelectionProblem.java
- FractionalKnapSack.java
- JobSequencing.java
public class SprialMatrix{
public static void main(String []args){
int [][]z = {{1,2,3,4,5},{6,7,8,9,10},{11,12,13,14,15},{16,17,18,19,20},{21,22,23,24,25}};
int x=5;
int y=5;
int a=0;
int b=0;
while(x>a && y>b){
for(int i=b;i<y;i++){
System.out.print(z[a][i]+" ");
}
a++;
System.out.println("");
for(int i=a;i<x;i++){
System.out.print(z[i][y-1]+" ");
}
y--;
System.out.println("");
for(int i=y;i>b;i--){
System.out.print(z[x-1][i-1]+" ");
}
b++;
System.out.println("");
for(int i=x-1;i>a;i--){
System.out.print(z[i-1][b-1]+" ");
}
x--;
System.out.println("");
}
}
}
> SpiralMatrix

- nearestElementInAnArray.c
Find nearest Smallest Element in an array for every element.
> nearestElementInAnArray.c

- ComparableInterface.java
Implementing Comparable Interface and overriding compareTo() to sort student records in java.
> ComparableInterface.java

- NumberOfIslands.java
Hey! I have created a program to count the number of islands using graph traversals. Please accept my pull request.
> NumberOfIslands.java

- HackerLandElections.java
package Strings;
import java.util.HashSet;
public class AllPossibleSubstrings {
static HashSet<String> strings;
static {
strings=new HashSet<String>();
}	
public static void generateSubstrings(String a,String b) {
/*if(b.length()==0)return;
if(a.length()==0)return;*/
for(int i=0;i<b.length();i++) {
String temp=a.concat(String.valueOf(b.charAt(i)));
strings.add(temp);
generateSubstrings(temp,b.substring(i+1, b.length()));
}
}
public static void main(String[] args) {
String str="kincenvizh";
int n=str.length();
for(int i=0;i<n;i++) {
strings.add(String.valueOf(str.charAt(i)));
generateSubstrings(String.valueOf(str.charAt(i)), str.substring(i+1, n));
}
System.out.println("Total Substrings are "+strings.size());
for(String s:strings) {
System.out.println(s);
}
}
}
> AllPossibleSubstrings.java

- reverse-word-string.java
> Created New File - Reverse-word-string.java

- Anonymous/RadixSort.java
> RadixSort.java

- Anonymous/DFSGraph.java
applied some clean coding principles
> Updated DFSgraph

- LeetCode/287. Find the Duplicate Number.java
https://leetcode.com/problems/find-the-duplicate-number/
> Add 287. Find the Duplicate Number

- LeetCode/1383. Maximum Performance of a Team.java
https://leetcode.com/problems/maximum-performance-of-a-team/
> Create 1383. Maximum Performance of a Team

- LeetCode/958. Check Completeness of a Binary Tree.java
https://leetcode.com/problems/check-completeness-of-a-binary-tree/
> Create 958. Check Completeness of a Binary Tree.java

- LeetCode/100. Same Tree.java
https://leetcode.com/problems/same-tree/
> Create 100. Same Tree.java

- LeetCode/138. Copy List with Random Pointer.java
https://leetcode.com/problems/copy-list-with-random-pointer/
> Create 138. Copy List with Random Pointer.java

- LeetCode/746. Min Cost Climbing Stairs.java
https://leetcode.com/problems/min-cost-climbing-stairs/
> Create 746. Min Cost Climbing Stairs.java

- LeetCode/70. Climbing Stairs.java
https://leetcode.com/problems/climbing-stairs/
> Create 70. Climbing Stairs.java

- LeetCode/658. Find K Closest Elements.java
https://leetcode.com/problems/find-k-closest-elements/
> Create 658. Find K Closest Elements.java

- LeetCode/127. Word Ladder.java
https://leetcode.com/problems/word-ladder/
> Create 127. Word Ladder.java

- LeetCode/130. Surrounded Regions.java
https://leetcode.com/problems/surrounded-regions/
> Create 130. Surrounded Regions.java

- LeetCode/1375. Number of Times Binary String Is Prefix-Aligned.java
https://leetcode.com/problems/number-of-times-binary-string-is-prefix-aligned/
> Create 1375. Number of Times Binary String Is Prefix-Aligned.java

- LeetCode/1304. Find N Unique Integers Sum up to Zero.java
https://leetcode.com/problems/find-n-unique-integers-sum-up-to-zero/
> Create 1304. Find N Unique Integers Sum up to Zero.java

- LeetCode/116. Populating Next Right Pointers in Each Node.java
https://leetcode.com/problems/populating-next-right-pointers-in-each-node/
> Create 116. Populating Next Right Pointers in Each Node.java

- LeetCode/103. Binary Tree Zigzag Level Order Traversal.java
https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/
> Create 103. Binary Tree Zigzag Level Order Traversal.java

- LeetCode/733. Flood Fill.java
https://leetcode.com/problems/flood-fill/
> Create 733. Flood Fill.java

- LeetCode/239. Sliding Window Maximum.java
https://leetcode.com/problems/sliding-window-maximum/
> Create 239. Sliding Window Maximum.java

- LeetCode/20. Valid Parentheses.java
https://leetcode.com/problems/valid-parentheses/
> Create 20. Valid Parentheses.java

- LeetCode/652. Find Duplicate Subtrees.java
https://leetcode.com/problems/find-duplicate-subtrees/
> Create 652. Find Duplicate Subtrees.java
